server:
  port: 8763

spring:
  application:
    name: home_service

eureka:
  client:
    serviceUrl:
      defaultZone: http://bachelordesign:admin12580@localhost:8761/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000