server:
  port: 8764

spring:
  application:
    #    反人类设定 不能用_，否则eureka找不到服务啊
    name: music-service
  datasource:
    name: bachelor_degree_design
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://120.77.254.189:3306/bachelor_degree_design?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root123
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  #redis 配置
  redis:
    database: 0
    host: 120.77.254.189
    password: foobared
    port: 6379
    jedis:
      pool:
        max-active: 1024
#        连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: 10000
#        最大空闲链接
        max-idle: 200
#        最小空闲链接
        min-idle: 20
    timeout: 50000
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.wayne.music_service.model  # 注意：对应实体类的路径

eureka:
  client:
    serviceUrl:
      defaultZone: http://bachelordesign:admin12580@localhost:8761/eureka/

#redis 配置